### ISSUE TITLE
Trivia minigame suggestion

### ISSUE THREAD

**Issue by UrUgli** [gemidyne/microtf2#105]
A small trivia question will be asked (related to TF2 or even warioware). And you will have 4 doors (once entered you can't switch).

Example : What is TF2 release date (year)

A - 2007
B- 2008 
C- 1998 
D - 2010

If the wrong door is chosen, the player will die over 3/4 seconds in the death zone (so it doesn't give away the answer to others).

The good door leads to a "nice" place ( i don't have an idea yet)

**Comment by stevu236** [comment]
I think this would work best as a bossgame - we actually had an idea to do this back for 2014 edition but the idea was scrapped. 

Expanding on your idea above, I think each doorway should lead to a glass room or platform with invisible walls surrounding. There will be a timer that counts down, and eventually all doors closed so players cannot change their answer once they're in their answer room. Those in the wrong one will die, and then all remaining are teleported out for the next question. I think this approach works better rather then decaying player's hp if they're in the wrong answer.

This would be repeated 3 or 4 times (?), afterwards the bossgame would end. Thoughts? @UrUgli @Mario6493

**Comment by Mario6493** [comment]
It might work, though after playing for a while everyone would know all the answers

**Comment by UrUgli** [comment]
Ah, that it is indeed true, but if you put a certain number, i think it would be fine.

**Comment by UrUgli** [comment]
@stevu236 I like this idea, so they are in a room and teleported upon answering right and killed if wrong. Is that so ?

**Comment by stevu236** [comment]
yeah - but as Mario said we need to have a lot of questions to make this to work. We can manually define these questions but im wondering if we should maybe look further afield for this.

I had an idea of using an API to instead provide questions for the gamemode: https://opentdb.com 

This would mean the questions are always different and no one can easily lookup this github repo and refer to it for answers. This may make this boss really difficult though.

**Comment by stevu236** [comment]
Had a discussion with the team, using opentdb's video game category will be the best way forward.

**Comment by wistlyr** [comment]
personally i'd think it'd be even more fun for trivia answers to be configurable by server operators.
could result in some funny community related questions and answers.

**Comment by stevu236** [comment]
Thats true. Maybe we can have a combination of API provided questions, and predefined questions.

**Comment by stevu236** [comment]
Re-reviewing this one. I think there is a bit of a problem here - specifically in terms of localisation / translations. 

In the past the gamemode only supported English which would make this one easy to implement - but with other languages on board we would need to maintain a large bank of questions & answers for every language (as the API mentioned in this thread does not support other cultures). This would also increase the work for translating a new language. 

For now, I think its best to close this one and maybe revisit in the future
