### ISSUE TITLE
Explosive jump minigame suggestion

### ISSUE THREAD

**Issue by UrUgli** [gemidyne/microtf2#106]
Everyone is demoman with stock (or iron bomber if possible). A fence is in front of them, the only way of getting beyond and on the win area is by doing a grenade jump (shoot at the ground and jump at the right time)

Example : 

![ezgif com-video-to-gif (2)](https://user-images.githubusercontent.com/45695904/57985283-d8da9500-7a65-11e9-953d-453592e6a734.gif)

**Comment by stevu236** [comment]
Good idea! Back in 2014 we had something similar but it wasnt as fleshed out as your idea.

Our idea was on a mountain and players had to jump across to the other end. They were scouts, but it couldn't be completed due to a bug with the map so was ultimately scrapped.

Your idea though _is_ fleshed out completely, and will be implemented into 2019.2.

**Comment by Mario6493** [comment]
I'm not sure it would work, the explosions from all the other players' grenades would send people flying everywhere except where they want to go

**Comment by UrUgli** [comment]
Not really, if you would put barriers in between, i think it would block the unneeded bounces.

**Comment by stevu236** [comment]
I don't think we need barriers. I think we just need to ensure the spawn area is large enough with enough space inbetween each spawn point.. like the target practice boss i guess.

Of course, we will see when we do play testing on this idea.

**Comment by UrUgli** [comment]
Glad you like the idea at least !

**Comment by stevu236** [comment]
Might be possible to apply the same weapon attribute to nullify damage to others that the rocket/sticky jumper uses when giving players the weapon

**Comment by stevu236** [comment]
Whilst this was pushed back multiple times I'm hoping to get it implemented as part of v5.0. Just planning out a map area for it now.

**Comment by stevu236** [comment]
TODO:
Mirror spawn area, and keep a single team on each spawn area. This prevents the projectiles exploding.

**Comment by stevu236** [comment]
BGM choice: Ape Escape 3 - Char Select (Tra. 75)

**Comment by stevu236** [comment]
Todo: make the platform slightly larger as its really difficult right now
