### ISSUE TITLE
Bloodthirst minigame suggestion

### ISSUE THREAD

**Issue by UrUgli** [gemidyne/microtf2#109]
You are all scouts equipped with the guillotine, everyone has the bleeding effect on them, and everyone is covered in milk. Only way to survive is to hit someone with the guillotine and effectively gaining health.

Example  : 
![ezgif com-video-to-gif (7)](https://user-images.githubusercontent.com/45695904/57985931-24457100-7a6f-11e9-956a-03e0d7f791c1.gif)

**Comment by stevu236** [comment]
Could be integrated into boston basher microgame
