### ISSUE TITLE
Co-op sap a building minigame

### ISSUE THREAD

**Issue by UrUgli** [gemidyne/microtf2#116]
Two teams: Spy and engineer
Engineers are told to build anything (or specific) and to get it sapped by a Spy.
Spy need to sap a building to win.

Spy example : 
![ezgif com-video-to-gif (11)](https://user-images.githubusercontent.com/45695904/58027162-52cb5680-7b18-11e9-8336-8f8e1a001f6d.gif)

Engineer example : 
![ezgif com-video-to-gif (10)](https://user-images.githubusercontent.com/45695904/58026988-f9632780-7b17-11e9-9028-3cf5dd857a6d.gif)

Kinda similar to the medic hit heavy minigame.

**Comment by stevu236** [comment]
This'll work - i think it'll take place in the main room. I think this can get done for 2019.2

**Comment by stevu236** [comment]
Dev note: Planning for this to replace the unused minigame 14 indice. Will close #37 when complete
