### ISSUE TITLE
BGM Boxing boss falls short (if fight is dragged on)

### ISSUE THREAD

**Issue by UrUgli** [gemidyne/microtf2#117]
The BGM on the boxing fight is too short if the fight goes on after a certain period of time.

**Comment by stevu236** [comment]
I agree, but i think this boss needs a further rethink.

**Comment by UrUgli** [comment]
A rethink ? In what way ?

**Comment by stevu236** [comment]
I think.. players move around too fast to punch another player. I feel that some tweaks need to be done so players are able to properly melee without running past each other

**Comment by UrUgli** [comment]
I think the speed is fine, i like it that you are fast enough, however i feel the punches should be a bit stronger and the drain rate slower as sometimes you hit someone 60 times before they die.

**Comment by stevu236** [comment]
Closing this as the original boss has been removed
