### ISSUE TITLE
Suggestion to change the factory BGM

### ISSUE THREAD

**Issue by UrUgli** [gemidyne/microtf2#118]
In my opinion, the music should feel more "YOU NEED TO ESCAPE" rather than "You're in a factory", that's what the current music feels to me. Knowing the context i think it should be changed.

Suggestions : 

https://www.youtube.com/watch?v=Vztd7n6bjIY

https://www.youtube.com/watch?v=4bLZCLN1Lxc

https://www.youtube.com/watch?v=rHaNoRcyAiY (Maybe loop the 0 to 0:18 part ?)

https://www.youtube.com/watch?v=-QIoK29jBD8

**Comment by stevu236** [comment]
The boss BGM needs adjusting as it doesn't contain the alarm sound (and TF2 seems to refuse to play it)
I think we should try that first before completely switching the bgm for something else.

The boss BGM was used to recreate the following scenario https://youtu.be/E0qe4uDDMeU

**Comment by UrUgli** [comment]
Oh right, i wasn't aware of that, we'll see how it goes WITH the alarm, but even then i still think it doesn't fit that much, but that's just my opinion.

**Comment by UrUgli** [comment]
Fixed the missing alarm bug on BGM.

**Comment by stevu236** [comment]
I will close this issue for now. The BGM appears to be fine now with that alarm sound, but if you feel there is a better more suitable bgm for this boss, please feel free to reopen :)
