### ISSUE TITLE
[BUG] Sawblade minigame advantage

### ISSUE THREAD

**Issue by UrUgli** [gemidyne/microtf2#119]
You can see in this gif that the left side has an advantage, you cannot get hit by the saw (so it's much easier)

![ezgif com-video-to-gif (12)](https://user-images.githubusercontent.com/45695904/58033879-98425080-7b25-11e9-96a7-19b670e4ce2c.gif)

**Comment by stevu236** [comment]
I am going to close this issue - this area was refreshed in 2019.1 update and was rebalanced. Please try the latest update before reporting issues - chances are they were already fixed!
