### ISSUE TITLE
[BUG] Stun issue after end round win

### ISSUE THREAD

**Issue by UrUgli** [gemidyne/microtf2#121]
In the latest version of warioware, the stun after the end round win, seems to sometimes last until the first minigame starts, causing you, most of the time, to lose. Perhaps the stun duration not being refreshed with the new round or it just being too long.

**Comment by stevu236** [comment]
Ah right yes, this is fixed in the dev branch but wasn't backported into a 2019.1 hotfix release. will need to do that at some point

**Comment by stevu236** [comment]
Our release plans have changed - 2019.2 is going to release as a smaller update than originally intended.

This means that the fix will be distributed in 2019.2, and will not be backported in 2019.1 as a result. We recommend that 2019.2 is used as a resolution for this issue.
