### ISSUE TITLE
Target Practice Boss arena

### ISSUE THREAD

**Issue by Corioldon** [gemidyne/microtf2#127]
Current arena is barely big enough to work with 32 players (people sometimes stay in each other). However making the arena just wider would increase the distance between corners, so spies on one side would have a harder time aiming at barrels at the very end on the other side. Also sometimes barrels spawn really close, so in order to destroy them, you are forced to shot while jumping.
My proposal would be to rebuild it to something like this:
![arena](https://user-images.githubusercontent.com/52788465/61055341-91331280-a3f1-11e9-93e7-db160ea87074.png)
Where outer circle is the player area, inner circle being the barrel area.
This layout puts everyone in the same distance from center, making the playing field a bit more even. 
It'd also be better if barrels weren't able to spawn so close to players.

**Comment by stevu236** [comment]
Hi, 
We have reworked this boss area and now players face each other on opposite ends of the arena. This improves support for 32 players. 

We have not changed the arena to be shaped like a circle, however we would like to do this in an upcoming update - for the moment we have added 2 conveyor belts in the middle of the room which can transport the barrels from each side of the room, however I agree with your point that this still does not make the distance from the center equal. 
I would like to address this in the next update after v4.0 - we have a few major plugin changes for v4 that I would like to be released sooner than later. However, whilst collecting feedback on v4 post release we will work on redesigning this area to be more equally distanced as a circle arena.

This is how the rework currently looks - each team has their own side: 
![image](https://user-images.githubusercontent.com/3583562/82731213-17500300-9cfd-11ea-8789-ba8e854ed620.png)
