### ISSUE TITLE
Add convar to enable/disable bonus points

### ISSUE THREAD

**Issue by FortyTwoFortyTwo** [gemidyne/microtf2#129]
I imagine many of you likes the whole bonus points and want to keep it. However me and many of  us dislikes it, as bonus point heavily favours on typing/math minigames, while many other minigames doesn't have one. Whoever one person with low ping and quick maths usually win most of the round easily because of it.

I could make a Pull Request to add convar for it, but i want to hear what you think about it first.

**Comment by stevu236** [comment]
I had a chat with the guys in the team and we totally agree with your point. This should be an opt-in thing via convar. 

If you could make a PR for this, that would be great!
