### ISSUE TITLE
Idea to nullify ping advantage on type the word bossgame

### ISSUE THREAD

**Issue by Corioldon** [gemidyne/microtf2#134]
Players with higher ping have to wait a small amount of time before they get to see the new word, which is problematic when there's multiple people with similar typing speed AND different ping.
I suggest showing the upcoming word/words, so people with higher ping can already begin to type instead of waiting.
The layout ideas I had:

Type the word
word         
nextword
timeleft

or

Type the word
word         nextword
timeleft

**Comment by stevu236** [comment]
You're 100% correct, the latency causes this boss to be unfair. I will implement your idea into the next hotfix update.

**Comment by stevu236** [comment]
Changes released in 2019.2.1.2
