### ISSUE TITLE
Able to get stuck in platform bossgame, unable to die

### ISSUE THREAD

**Issue by FortyTwoFortyTwo** [gemidyne/microtf2#135]
![20190730232509_1](https://user-images.githubusercontent.com/33488710/62170127-40447900-b322-11e9-9ccc-3e8ba030751b.jpg)

I believe this happen the moment bossgame starts, knocked into a wall while platform closing off, and somehow stuck into it. Said they cant move around or do anything while stuck there.

**Comment by stevu236** [comment]
Thats interesting, do any other players get spawned outside of the platform? Does this only happen if you jump towards that platform while it closes?

**Comment by FortyTwoFortyTwo** [comment]
Don't think so, only when you jump into a platform while it closes
