### ISSUE TITLE
"Listen for it" minigame

### ISSUE THREAD

**Issue by stevu236** [gemidyne/microtf2#145]
Barrels (or other physic prop) should be spawned in the main room - with no BGM, players should listen for a prop emitting a sound. 

Players spawn with no weapons. Until a few seconds later when the caption changes to "Shoot the one making the sound" when they will be given weapons and the sound will stop. Upon shooting the correct prop, they will win the minigame. The props will be indestructible.

This minigame should run longer than other standard minigames.

**Comment by Mario6493** [comment]
Nice idea, but people could spam voice commands and make the sound hard to hear

**Comment by stevu236** [comment]
I think we could probably block those for the listen period - I will probably also need to add a new plugin forward so other plugins get notified of the "QuietPeriod"

**Comment by stevu236** [comment]
Similar to #147 - this minigame isnt that accessible for deaf players. We're gonna think a little bit more about this one, but not sure if this will make the cut
