### ISSUE TITLE
Dont Touch minigame

### ISSUE THREAD

**Issue by stevu236** [gemidyne/microtf2#146]
Whats the possibility of reviving the Dont Touch special round instead as a minigame?

This could work similar to the airblast minigame, but in a larger open space. If you're airblasted, and touch another player, you lose. 

What are your thoughts?

**Comment by Mario6493** [comment]
This could work!

**Comment by stevu236** [comment]
We probably need to add a check in so if players think they can change class or team to avoid, they are exempt from the game

**Comment by stevu236** [comment]
Note: minigame will have a brief period at the start where the check is not run. Players will be semi-transparent while this check is off, and will be opaque again when the check is active. This gives players a brief period to prepare.

**Comment by stevu236** [comment]
Todo: investigate limiting the fan's clip size to 1

**Comment by stevu236** [comment]
Also, this should only run on higher player counts.
