### ISSUE TITLE
Stand on a specific platform

### ISSUE THREAD

**Issue by stevu236** [gemidyne/microtf2#147]
The platforms in the main room could possibly have triggers added to them, allowing us to track if someone specifically steps onto them. (Similar to what we do with Win Areas now)

This could be morphed into a minigame so players have to get onto a green / red / etc platform. Probably will want to have collisions off for this to work out.

**Comment by Mario6493** [comment]
Even better idea: show a colored shape on screen ( green square, red circle, etc), the players need to get on that specific platform

**Comment by stevu236** [comment]
Under consideration we might abandon this one, due to colour blindness. Potentially, we could use symbols (like maybe well known game items as decals on the platforms) and refer to those instead of colours.

**Comment by stevu236** [comment]
We are gonna close this one off for now - maybe in the future it can return
