### ISSUE TITLE
Translator Request (Portuguese PTBR / PT)

### ISSUE THREAD

**Issue by EduardoKdinho** [gemidyne/microtf2#150]
Hello, I am a founder and owner of a bunch of populated servers in my country. I would like to contribute testing and with the translation PT / BR (Brazilian Portuguese) and PT (Portuguese of Portugal). If in case it is interesting for you of course. My steam profile: https://steamcommunity.com/id/duhbiluh

**Comment by stevu236** [comment]
Hi there!

Thanks for your interest in the gamemode! Localising the gamemode for more languages is one of our top priorities, so if you would like to help out with translations - it would be very much appreciated! 

If possible, contributing the translation file updates via GitHub is recommended, so your user account is linked with any contributions you make. If you are unable to contribute translations by this method though, we can share the translation file via other means. Once you have submitted translations to the plugin I will update the gamemode credits page with your name as the translator for PT/BR & PT.

The translation file for the plugin is best downloaded/edited from the dev branch: https://github.com/gemidyne/microtf2/blob/dev/src/translations/microtf2.phrases.txt


In regards to gamemode testing, we do have a Testers Group on Steam Community - https://steamcommunity.com/groups/microtf2_testers - if you send a request to join I will approve it. This group will have scheduled events and will notify you of any upcoming testing sessions.

Thanks again for wanting to contribute towards the development for the gamemode!

**Comment by stevu236** [comment]
Closed as #151 merged into dev branch
