### ISSUE TITLE
Plugin breaks killfeed/hitsounds/etc when not active

### ISSUE THREAD

**Issue by bakugo** [gemidyne/microtf2#171]
When not on the warioware map, the plugin is inactive but it still catches the `player_death` and `player_hurt` events in `EventHookMode_Pre` mode and returns `Plugin_Handled` which cancels them. This breaks the killfeed and hitsounds, and probably more stuff.

**Comment by stevu236** [comment]
Good catch - I didn't actually realise this was what was preventing the killfeed from displaying. I have updated the dev branch so it will display again.
