### ISSUE TITLE
Add optional bonus point for finishing bosses first

### ISSUE THREAD

**Issue by Mario6493** [gemidyne/microtf2#173]
My idea is adding a cvar that enables getting a bonus point for being the first to finish certain boss games.
The bosses that would award this bonus point would be Escape the Factory, Rocket Jump and Beatblock.

What do you think?

**Comment by stevu236** [comment]
We have a mtf2_bonuspoints cvar that controls this for Minigames 6 & 8 (Say the word & Maths) so this could be an extension of that. Will need a new translation string to be added I believe
