### ISSUE TITLE
Don't laugh - alternative objectives

### ISSUE THREAD

**Issue by stevu236** [gemidyne/microtf2#174]
I think you mentioned this during our test session (and I can't find a issue for this) - you had noticed that players all run from each other, essentially making the microgame really easy.

Should this microgame be updated so 25% of the server will be chosen to make people laugh (and in doing so, win the microgame), whilst other players have to dodge them?

If you think this would solve the problem - the chosen players should probably be the only ones as Heavy, whilst others are another class. Thoughts? @Mario6493

**Comment by Mario6493** [comment]
I wrote a comment of the existing issue for the minigame
https://github.com/gemidyne/microtf2/issues/94#issuecomment-629801343

Anyways, I like your idea!
Just gotta make sure to give crits to the heavies, also maybe increase their speed slightly so they can catch up to players

What I like about this is that this way, the heavies could either go for the players or hit another heavy making them possibly fail the minigame, should make for some funny situations

**Comment by stevu236** [comment]
> I wrote a comment of the existing issue for the minigame
> [#94 (comment)](https://github.com/gemidyne/microtf2/issues/94#issuecomment-629801343)

My bad sorry, I didn't see this in the discord feed
