### ISSUE TITLE
Missing water texture in dx8

### ISSUE THREAD

**Issue by bakugo** [gemidyne/microtf2#176]
When playing in dx8, the "green slime" water texture on the map shows up as a missing texture. This is because the vmt contains `"$fallbackmaterial" "nature/water_riverbed01_dx8"` but that material doesn't exist in TF2.

**Comment by stevu236** [comment]
I've had a look at the VMT and tested removing the $fallbackmaterial and it looked to display fine on dx80. It looked fine, so I have removed these lines from the slime VMT
