### ISSUE TITLE
Ovelays are opaque in dx8

### ISSUE THREAD

**Issue by bakugo** [gemidyne/microtf2#190]
The success/failure/etc overlay textures are opaque in dx8 and cover the entire screen.
Somehow I played this for months without realizing that this wasn't intentional lol

**Comment by stevu236** [comment]
We are currently looking into this. This is indeed a bug - we updated the overlays a while back to use masking so the text displayed would scale and keep good quality based on your screen resolution, but missed testing this on dxlevel80: 

![image](https://user-images.githubusercontent.com/3583562/93933397-8411f300-fd19-11ea-9453-bc6cc7b5e666.png)

**Comment by stevu236** [comment]
There's potentially a workaround by checking the player's mat_dxlevel - so we'll just fallback to using the standard HUD text with no overlays on DirectX 8 only, we will need to test this but might be a potential solution

**Comment by stevu236** [comment]
Hi,

We have tested & released a fix in [v4.2.0](https://github.com/gemidyne/microtf2/releases/tag/v4.2.0). Fallback text is now used for players running DirectX 8, whilst the existing overlays will still display for anyone running DX9.
 
My apologies for the delay in this getting fixed and released.
