### ISSUE TITLE
mp_timelimit should modified at a later time

### ISSUE THREAD

**Issue by stevu236** [gemidyne/microtf2#194]
We need to stop trying to write to mp_timelimit immediately on map start. We should delay this to when waiting for players start, so that gives enough time for configuration plugins to initialise the server environment

**Comment by worMatty** [comment]
Hi, Steveh. Have you tried OnConfigsExecuted?

**Comment by stevu236** [comment]
Hey, good call - I didn't realise that existed in SM. I will give that a try later on today and feedback here

**Comment by stevu236** [comment]
Sorry, I haven't had a chance to test this yet - its probably gonna be closer to the weekend before I can get around to this
