### ISSUE TITLE
I want to join the translators team

### ISSUE THREAD

**Issue by kingofings** [gemidyne/microtf2#206]
I want to become a translator for the gamemode and provide text for **German**.

My Steam Community Profile link is: **http://steamcommunity.com/profiles/76561198084783019**

- [x] I agree to provide accurate translations for my language

**Comment by stevu236** [comment]
Hi there,

Thanks for your interest in translating the gamemode! It is very much appreciated! 

I have set you up as our German translator. I can see you have already logged in to Gemidyne.com before - when logged in, if you click "Logged in as...", and then select "Contribute" from the dropdown menu, you should now see a Translate button. If you click that you will be able to submit translations for the gamemode using the web editor. 

We also have a Steam Group where we periodically notify translators of new strings that need to be translated for a release: 
https://steamcommunity.com/groups/wariowareredux_translators


Thanks again for helping with the gamemode! If you have any questions regarding the translations, or anything else - please feel free to add me on Steam ( https://steamcommunity.com/id/imstevu/ ) or raise an issue here.
