### ISSUE TITLE
How many of prop type boss

### ISSUE THREAD

**Issue by stevu236** [gemidyne/microtf2#207]
Originally a "russian roulette" style of boss - this boss would revolve around players looking at a set of props spawned randomly, and after a few seconds the props disappearing. 

Players would then be asked "How many <Type> were there?" - Type being dynamic, and a subset of the props being spawned. 

Players would then need to input their answer within X seconds. Their input method has not yet been decided: 
- Players could use chat - this would be the quickest way, however players could possibly change their answer at a moments notice unless we impose a restriction here
- Players could use an "answer room" - this would mean players would need to physically run into a set of 3 or 4 (TBD) rooms to select their answer. This adds physicality to their decision meaning by default they have a finite time of changing their answer as each change of mind would involve them changing rooms. If the player does not enter any room, they lose by default. 

Correct answering players would then go onto the next round within the boss, and the last standing would receive the boss point award.

Losing players would be knocked out and have to watch the others play.

Feedback would be most appreciated

**Comment by worMatty** [comment]
I like the second method more. I actually find chat text entry cumbersome.
I can make a mistake typing, but I can't make a mistake walking into a
room. With the room you also have a bit of uncertainty about what the
others are doing, and you might instinctively follow someone to their
answer if you think they're more likely to know it.

**Comment by stevu236** [comment]
- [ ] Add viewing time decay - 0.5 each round. Minimum time allowed is 2 seconds. 

Once we do the above we can advance to final playtest
