### ISSUE TITLE
Microgames (but not music) don't speed up/slow down

### ISSUE THREAD

**Issue by Doresun** [gemidyne/microtf2#215]
**Describe the bug**
While the music does speed up/slow down, the microgames themselves don't, resulting in either music ending abruptly or music overlapping (special rounds that slow down the game).

**Expected behavior**
Microgames speeding up/slowing down.

**Do you know what version of the gamemode this bug occurred on?**
 - Version: 4.2.1

**Additional info**
This occurs on both Windows and Linux dedicated servers.

**Comment by stevu236** [comment]
Just to double check, are there any error logs from SourceMod while you see this issue?

Usually this behaviour can indicate there might be a problem somewhere else causing things to not run properly.
