### ISSUE TITLE
Main Room clipping

### ISSUE THREAD

**Issue by TuxoYKT** [gemidyne/microtf2#216]
**Describe the bug**
In the main area players can get stuck in some angled clip brushes if they keep their velocity at the specific angle. This allows players to bypass and win the "Get to the platform" minigame if they get stuck in the higher area since the floor can't get them. Also it gives unfair advantages in "Don't laugh" and "Avoid kamikaze" minigames since players are unreachable for other players. 

**Expected behavior**
Players shouldn't get stuck.

**Additional info**
This is a known bug in Source.

**Comment by TuxoYKT** [comment]
Create two brushes between the center of the room.
![hammerplusplus_y4eRGDrRDU](https://user-images.githubusercontent.com/6498761/131202400-2611651e-2200-4967-927c-c27eb1924535.png)

Tilt them towards the center. (You can use Vertex Tool)
![hammerplusplus_qGlY4Jk4zg](https://user-images.githubusercontent.com/6498761/131202415-0e32bb51-834d-4736-9036-cf7c7bcc897e.png)

Group them(Ctrl+G) and copy. Then "Paste Special..." with these settings.
![hammerplusplus_u1WsgMQejS](https://user-images.githubusercontent.com/6498761/131202443-c0e608b0-c883-4b82-8a66-385ca7ac5915.png)

After that you should get something like this.
![image](https://user-images.githubusercontent.com/6498761/131202666-278ed476-aff0-4c3c-ac41-3c88fb2f0cfc.png)

**Comment by stevu236** [comment]
Awesome! Thanks for the instructions, very much appreciated! I got it now - this fix will be in the v5 version of the map. 
![image](https://user-images.githubusercontent.com/3583562/131212725-6b420275-e812-4b8b-bb1d-d0b60a5490a3.png)

V5 has been rescoped so should be released within the next month.
