### ISSUE TITLE
Players always win in Count the prop

### ISSUE THREAD

**Issue by whysodrooled** [gemidyne/microtf2#220]
**Describe the bug**
When the count the prop is played, it always ends up with everybody being winners.
I initially thought it was the death timing was not right, but even if I die earlier than other players, I still won.

**Expected behavior**
Only the survivors remaining last should win.

**Do you know what version of the gamemode this bug occurred on?**
 - Version: ac26e19 of dev branch (Regen translations), used master branch for Bossgame8.sp

**Additional info**
On line 285 of Bossgame8.sp, it seems like player.IsAlive isn't functioning well in this case for whatever reason.
I replaced player.IsAlive to player.Status == PlayerStatus_NotWon and it worked well.

**Comment by stevu236** [comment]
Thanks for the report. I agree this should be referring to status instead. I'll get master updated and release a hotfix update.
