### ISSUE TITLE
Playing the Rocket Jumping boss game with 32 players will cause some players spawning in walls

### ISSUE THREAD

**Issue by KayaDLX** [gemidyne/microtf2#228]
**Describe the bug**
Whenever we're playing with a full 32 players lobby, and having the Rocket Juming boss game, approximately 3-4 players are always getting stuck in the walls upon spawning, which I have to `sm_bring` them quickly out of the walls before the kill trigger rises up and kills them.

**Expected behavior**
All 32 players should be teleported in the correct spot.

**Comment by stevu236** [comment]
Good find! I have fixed the coordinates used. (Release pending. I think it will go out along with the path change for #227) 

But just to be sure, I will go through the other bosses to double check the spawns for those too.

**Comment by KayaDLX** [comment]
Alright! Thanks for that :)

**Comment by stevu236** [comment]
A fix for this has been pushed as part of release v5.2.0: https://github.com/gemidyne/microtf2/releases/tag/v5.2.0
