### ISSUE TITLE
Map seems to be having some missing mp3 issues here.

### ISSUE THREAD

**Issue by gdfsgdfg** [gemidyne/microtf2#234]
![Untitled](https://user-images.githubusercontent.com/8344799/165865729-e4a8a538-70a3-4146-a7b9-89204510b6fd.png)

**Comment by stevu236** [comment]
This can happen if the gamemode is not installed on the server correctly, or that your client-side sound caches have become corrupt. 

Client-side audio cache corruption happens rarely, but has been seen before. Try deleting any sound.cache files in your local client TF2 folder. 

If the issue persists, this is most likely a gamemode install issue on the server - the install guide can help in those cases: https://github.com/gemidyne/microtf2/wiki/How-to-install-the-gamemode

**Comment by gdfsgdfg** [comment]
All sound.caches are cleared I know about that bug myself, it only seems that the typing word minigame is the one missing the mp3s. If you don't have on your side then I'm not sure.

I am using the map from releases and compiled the newest plugin version ya got there.

**Comment by stevu236** [comment]
I have been looking more about this...

Source is saying it is failing to load `{.wav`, `}.wav` and `version.wav`. We use a {version} tag in sound paths within the plugin that means that when we release a new version of the plugin & map, all new paths are used, so we sidestep the Source sound cache corruption bug

An example path in the screenshot you provide should be: 
```#define BOSSGAME7_SFX_BOSS_START "gemidyne/warioware/{version}/bosses/sfx/drpa_bossstart.mp3"```

 The {version} tag above is replaced with the current gamemode version (`v5_2b`), so this path should become: 
`#define BOSSGAME7_SFX_BOSS_START "gemidyne/warioware/v5_2b/bosses/sfx/drpa_bossstart.mp3"`
This indicates that the plugin is not doing that {version} token replacement at all. 

From looking at the source code it looks like this is indeed a bug, as I can see it doing the token replacement when it's preloading the sounds, but not when playing in certain cases. 

I'll keep looking into it and keep you updated

**Comment by stevu236** [comment]
I have pushed an optional [release](https://github.com/gemidyne/microtf2/releases/tag/v5.2.4) which should fix this

**Comment by gdfsgdfg** [comment]
Nice, I'll see the outcome if people vote for wario again.
