### ISSUE TITLE
trigger_hurt in prop bossgame not covering whole area

### ISSUE THREAD

**Issue by FortyTwoFortyTwo** [gemidyne/microtf2#240]
**Describe the bug**
In prop counting bossgame, there a spot that is not being covered from trigger_hurt, so players were able to stand on it to survive whole bossgame.

**Expected behavior**
trigger_hurt to cover this spot.

**Screenshots**
![microtf2](https://user-images.githubusercontent.com/33488710/191039817-a62ae41e-4087-4e6f-93e0-45e5a83fc383.png)

**Do you know what version of the gamemode this bug occurred on?**
 - Version: v5.2.6 (with map filename warioware_redux_v5b)

**Additional info**
I made a [commit](https://github.com/FortyTwoFortyTwo/microtf2/commit/e593666a8a8aae7253e5895177d067d2b0856581) on fixing it by just extending trigger_hurt borders to it, but I might've not configured my hammer correctly as it showing a lot more diffs than I expected, but it should be an easy fix for any devs to solve it anyway.

**Comment by stevu236** [comment]
Bugfix released in https://github.com/gemidyne/microtf2/releases/tag/v5.2.7 - requires map update `warioware_redux_v5c`
