### ISSUE TITLE
Not enough space on the heap

### ISSUE THREAD

**Issue by NyxNyxNyxNyxNyxNyx** [gemidyne/microtf2#241]
Using the latest release of the mod (5.2.6) and SM 1.11, still getting the bug unfortunately.

Here's the error as it appears in the console:

L 09/22/2022 - 21:43:34: [SM] Exception reported: Not enough space on the heap
L 09/22/2022 - 21:43:34: [SM] Blaming: AS-MicroTF2.smx
L 09/22/2022 - 21:43:34: [SM] Call stack trace:
L 09/22/2022 - 21:43:34: [SM]   [1] Line 245, D:\src\gemidyne\tsukuru\sm-env\SourcePawnENV_1.11\include\morecolors.inc::CReplaceColorCodes
L 09/22/2022 - 21:43:34: [SM]   [2] Line 49, D:\src\gemidyne\tsukuru\sm-env\SourcePawnENV_1.11\include\morecolors.inc::CPrintToChat
L 09/22/2022 - 21:43:34: [SM]   [3] Line 623, MethodMaps\Player.inc::Player.PrintChatText
L 09/22/2022 - 21:43:34: [SM]   [4] Line 64, Minigames\Minigame13.sp::Minigame13_OnMinigameFinishPre
L 09/22/2022 - 21:43:34: [SM]   [6] Call_Finish
L 09/22/2022 - 21:43:34: [SM]   [7] Line 872, D:\src\gemidyne\microtf2\src\scripting\AS-MicroTF2.sp::Timer_GameLogic_OnPreFinish
L 09/22/2022 - 21:43:36: [SM] Exception reported: Not enough space on the heap
L 09/22/2022 - 21:43:36: [SM] Blaming: AS-MicroTF2.smx
L 09/22/2022 - 21:43:36: [SM] Call stack trace:
L 09/22/2022 - 21:43:36: [SM]   [1] Line 245, D:\src\gemidyne\tsukuru\sm-env\SourcePawnENV_1.11\include\morecolors.inc::CReplaceColorCodes
L 09/22/2022 - 21:43:36: [SM]   [2] Line 49, D:\src\gemidyne\tsukuru\sm-env\SourcePawnENV_1.11\include\morecolors.inc::CPrintToChat
L 09/22/2022 - 21:43:36: [SM]   [3] Line 623, MethodMaps\Player.inc::Player.PrintChatText
L 09/22/2022 - 21:43:36: [SM]   [4] Line 240, Hud.sp::Timer_Advertise

**Comment by stevu236** [comment]
Thanks for reporting, I will look into it.

**Comment by NyxNyxNyxNyxNyxNyx** [comment]
I should probably also point out that this happens exclusively at round end, causing said end of round to continue indefinitely. Apologies, I should've included it in the initial report.

**Comment by stevu236** [comment]
I have created a branch with a potential fix for this. I have tested these changes on my own server with SM 1.11 and do not see any issues. If possible before I merge the PR in, would you be able to give it a try to confirm if this resolves the problem for your server? 

A build can be downloaded from this link: https://github.com/gemidyne/microtf2/actions/runs/3123040577

**Comment by NyxNyxNyxNyxNyxNyx** [comment]
Been playing a few rounds and it's going without any problems now! So seems to be resolved!

**Comment by stevu236** [comment]
Glad to hear it - I will look to create a release tomorrow with these fixes integrated. Thanks for testing!

**Comment by stevu236** [comment]
Bugfix released in https://github.com/gemidyne/microtf2/releases/tag/v5.2.7
