### ISSUE TITLE
Voodoo-Cursed Souls aren't removed together with the cosmetics

### ISSUE THREAD

**Issue by Tiagoquix** [gemidyne/microtf2#250]
**Describe the bug**
[Voodoo-Cursed Souls](https://wiki.teamfortress.com/wiki/Voodoo-Cursed_Soul) aren't removed with the cosmetics. This makes players half invisible.

**Expected behavior**
Voodoo-Cursed Souls should be removed together with the cosmetics to avoid the invisibility bug and render the players properly.

**Screenshots**
![image](https://github.com/gemidyne/microtf2/assets/30274161/b9cd8cee-4350-47a2-80b6-0fef862b2cce)

**Do you know what version of the gamemode this bug occurred on?**
- Version: 5.2.8

**Additional info**
No additional info.

**Comment by safalin1** [comment]
This should be fixed in release v5.2.9: https://github.com/gemidyne/microtf2/releases/tag/v5.2.9

I have done limited testing with it and am not seeing any issues, but if there are any problems do let me know and I can reopen this issue 👍
