### ISSUE TITLE
Remove setting values for sm_mapvote_extend and sv_use_steam_voice

### ISSUE THREAD

**Issue by Tiagoquix** [gemidyne/microtf2#259]
**Describe your enhancement to the gamemode**

File: https://github.com/gemidyne/microtf2/blob/master/src/scripting/ConVars.sp

`sm_mapvote_extend` should not be modified by the plugin. It should be up to the server operator to decide whetever or not the game mode will have the extend option in the map vote.

`sv_use_steam_voice` is deprecated:
> ] sv_use_steam_voice
 "sv_use_steam_voice" = "0"
 replicated
> - Deprecated - placeholder convar for handling old network streams that had an incomplete

The new ConVar is `sv_voicecodec` and the default value is `steam`.
> ] sv_voicecodec 
"sv_voicecodec" = "steam"
> - Specifies which voice codec to use. Valid options are:
vaudio_speex - Legacy Speex codec (lowest quality)
vaudio_celt - Newer CELT codec (22kHz, 22kbps)
vaudio_celt_high - Newer CELT codec, higher bitrate (44kHz, 44kbps)
steam - Use Steam voice API

I have been playing on a server which uses `sv_voicecodec vaudio_celt` for the music bot and it never had a problem with MicroTF2.

**Describe alternatives you've considered**

No possible alternatives.

**Additional context**

No additional context.

**Comment by safalin1** [comment]
These convars being set is most likely an oversight from many years ago so these should be fine to remove - we'll aim to get this out in a minor release before v6

**Comment by safalin1** [comment]
These convars will no longer be set by the plugin in v5.2.10 - https://github.com/gemidyne/microtf2/releases/tag/v5.2.10
