### ISSUE TITLE
Create a new ConVar to control mp_forcecamera separately

### ISSUE THREAD

**Issue by Tiagoquix** [gemidyne/microtf2#260]
**Describe your enhancement to the gamemode**

File: https://github.com/gemidyne/microtf2/blob/master/src/scripting/ConVars.sp

Currently, the plugin sets `mp_forcecamera 0`. I would like to have a ConVar so I would be able to dictate what the plugin does to this specific ConVar.

Something like: `mtf2_forcecamera_setting <0/1/2>`, with the default being the current value (`0`).
As far as I know, `mp_forcecamera 2` fades the death cam to black. I don't know if `mp_fadetoblack 1` is needed for it to work.

**Describe alternatives you've considered**

Do not force the value to `0` and let server operators decide. (But I prefer my original suggestion.)

**Additional context**

Target IDs do not work with `mp_forcecamera 0` for enemies and I think this is not nice.

**Comment by safalin1** [comment]
This has been removed in v5.2.10 - https://github.com/gemidyne/microtf2/releases/tag/v5.2.10
