### ISSUE TITLE
Reduce "waiting for players" time to 60 seconds

### ISSUE THREAD

**Issue by Tiagoquix** [gemidyne/microtf2#261]
**Describe your enhancement to the gamemode**

Reduce "waiting for players" time to 60 seconds.

**Describe alternatives you've considered**

Maybe 45 seconds instead of 60?

**Additional context**

The current time is a little too long and there are people who join the server/map quickly (due to having a good PC) and already have the map downloaded.

**Comment by safalin1** [comment]
We'll look to make this configurable in an upcoming update; we will reduce this to 60 seconds by default, but add a new convar so server operators can adjust this to their needs

**Comment by safalin1** [comment]
We've created a new v5 release which adds this ConVar: `mtf2_waitingforplayers_time`

Release: https://github.com/gemidyne/microtf2/releases/tag/v5.2.11
