### ISSUE TITLE
I want to join the translators team

### ISSUE THREAD

**Issue by OWATANKS** [gemidyne/microtf2#267]
I want to become a translator for the gamemode and provide text for **한국어**(Korean).

My Steam Community Profile link is: **https://steamcommunity.com/id/6669001/**

- [O] I agree to provide accurate translations for my language

**Comment by safalin1** [comment]
Hello - thank you for your interest in contributing! We really appreciate it.

We have a web translator tool that will make it easy for you to add translations: https://translator.gemidyne.com/

Click the Sign in through Steam button to be taken to Steam Community to complete your login. Once you have logged in using the same account you linked above, you will be redirected back to our translator tool where you should be able to see Microgames in Team Fortress 2 on the homepage:

![image](https://github.com/user-attachments/assets/b32d7df1-49c9-4b16-91ff-a4b2493eb61a)
Click the View/edit project button, and then click Edit translations on KO to start submitting translations. There are quite a lot so the page might take time to load.

![image](https://github.com/user-attachments/assets/abf866e0-9aad-4bba-8fa9-2aa697feca59)
Once you are finished, click the Commit translations button on the right to submit your translations.

If you encounter any issues, feel free to @ me on Github and I can assist 👍

**Comment by safalin1** [comment]
Apologies - there was a configuration error on our end. You should now have access if you try again.

**Comment by OWATANKS** [comment]
@[safalin1]
oh thank you! 
And should I translate these files in this microtf2/data file and send it to you?
![78890](https://github.com/user-attachments/assets/1a3c9ca6-ffa6-4169-8297-1a9fc7bca2eb)

**Comment by safalin1** [comment]
No at the moment those are configuration files - they do not currently support translations. Server operators can manually change the words in Bossgame7's Dictionary files and Minigame6's Answers file if they wish but we do not currently distribute translations for those

**Comment by OWATANKS** [comment]
ok, so my translation on web translator is ended(https://translator.gemidyne.com/), so i guess thats my work too... thank you.

**Comment by safalin1** [comment]
Thanks again for your contribution. We are hoping to resume development on Version 6 of the gamemode soon, and we will be looking for more/updated translations in Korean. 

If you are willing to provide translations again in the future, we can keep access assigned to your Steam account on the Translator tool so you can update/amend the translations anytime - its up to you.
