### ISSUE TITLE
Typing Speed boss

### ISSUE THREAD

**Issue by stevu236** [gemidyne/microtf2#59]
Inspired by Danganronpa, all players will be spawned in a circle, and must type out a series of sentences the fastest. When a sentence is spoken, they will have 5(?) seconds to answer.

It is then up to players to write the sentence as fast as they can. If a player fails to type the sentence in time, they will be eliminated. If everyone types the sentence in fast enough, the slowest player will be eliminated.

As the boss goes on, the sentences will get longer to eliminate more players.

**Comment by stevu236** [comment]
@Mario6493 How many rounds in the boss should there be?

**Comment by Mario6493** [comment]
> 
> 
> @Mario6493 How many rounds in the boss should there be?

As many as needed until there's only one player left

**Comment by stevu236** [comment]
OK so, it looks like we might be able to emulate Danganronpa's iconic class trial opening camera spin - we should learn from https://forums.alliedmods.net/showthread.php?t=204418. This plugin is able to set the camera for a player onto another entity. We would want to do that too, but onto say, a tracktrain embedded within the map.

**Comment by stevu236** [comment]
To be linked into map areas via Factory boss spawn area

**Comment by stevu236** [comment]
This is currently on the dev branch, had a testing session with the testers group and it went pretty smoothly.

We still need to:

- [ ] Implement word category dictionaries
- [ ] Implement difficulty levels
- [ ] Implement final round review, where the winner is announced
- [ ] Extend existing round review, allow for word category/difficulty level selection text

**Comment by stevu236** [comment]
We also need to
- [ ] Add round review music (Our Class Trial / Underground Trial BGM)
- [ ] Add an overlay for the spiral sequence (Should say something like.. Rapidfire Word Attack?)
- [ ] Properly stop players from moving

**Comment by UrUgli** [comment]
- If you had the difficulty levels, i think they should be stated before they new round starts. Same goes for first round
- Selection for a difficulty/category should maybe be doors so you can vote by choosing the specific one ?
- Maybe forcetaunting everyone would be nice, so it can prevent them from moving, and work like an "introduction" when starting

**Comment by stevu236** [comment]
I think having doors to select a difficulty or category is a bad idea. We don't have a map area planned for that and it wouldn't add much to this boss if im honest

But i agree when difficulty is selected it should be stated. Thats something im going to add in soon to the boss

**Comment by stevu236** [comment]
We are going to be wrapping up any changes to this boss very soon. 2019.2 has to be ready by the end of June so any major changes will need to wait until after this date

**Comment by stevu236** [comment]
TODO: Need to handle class changes

**Comment by stevu236** [comment]
TODO: Need to handle class changes
