### ISSUE TITLE
Say Microgame have rare chance to roll nothing

### ISSUE THREAD

**Issue by FortyTwoFortyTwo** [gemidyne/microtf2#63]
in this line, an empty string after the last/max/count string have a chance to appear
https://github.com/gemidyne/microtf2/blob/master/src/scripting/Minigames/Minigame6.sp#L29
```
Format(Minigame6_SayTextAnswer, sizeof(Minigame6_SayTextAnswer), Minigame6_SayTextAnswers[GetRandomInt(0, Minigame6_SayTextAnswerCount)]);
```
should have been like this, adding -1 at the end
```
Format(Minigame6_SayTextAnswer, sizeof(Minigame6_SayTextAnswer), Minigame6_SayTextAnswers[GetRandomInt(0, Minigame6_SayTextAnswerCount-1)]);
```

**Comment by stevu236** [comment]
We just got this in our testing session too, good catch.
