### ISSUE TITLE
Players can stealthjoin or leave/rejoin during Lowest Score Wins to cheat the Special Round

### ISSUE THREAD

**Issue by EgocentricPoliceDick** [gemidyne/microtf2#70]
One of our runs with the plugin showed players leaving/rejoining to get a score of 0 during Lowest Score Wins - we've counteracted this by changing line **226** of `AS-MicroTF2.sp` from:
```sp
if (!player.IsParticipating && SpecialRoundID != 17)
```
to
```sp
if (!player.IsParticipating && SpecialRoundID != 9 && SpecialRoundID != 17)
```
(probably worth changing the comments roundabout those lines.)

**Comment by stevu236** [comment]
good catch! Will add this in just now
