### ISSUE TITLE
The factory boss minigame should be harder

### ISSUE THREAD

**Issue by UrUgli** [gemidyne/microtf2#72]
This boss feels a bit too easy. Some rooms are just empty and straight forward. My suggestions are:

- Make the laser insta death on the "Escape the factory" boss minigame
- Maybe add saws on some of the earlier parts to make it less of a stroll down a corridor
- Add a laser pattern trap

**Comment by UrUgli** [comment]
Here add some sort of anti-afk, make the floor break if pepole don't move in under >5 seconds or so. A motivator going at a pretty decent speed could also help making it harder and tense

![20190323190618_1](https://user-images.githubusercontent.com/45695904/54869875-ef82a980-4d9e-11e9-8ae4-4e0bc1ba9ffe.jpg)

Those two corridors just take up time and have nothing challenging, maybe have buzzsaws on the first corridor and lasers with patterns on the second one.

![20190323190631_1_LI](https://user-images.githubusercontent.com/45695904/54869909-68820100-4d9f-11e9-8eb4-3655a887cf9e.jpg)
![20190323190638_1_LI](https://user-images.githubusercontent.com/45695904/54869922-97987280-4d9f-11e9-8e9d-6a3cce40c823.jpg)

Here rather than a giant slide, you can have a part with moving platforms as drawn (im on a mouse, sorry if its horrible)
![20190323191327_1_LI](https://user-images.githubusercontent.com/45695904/54869940-fa8a0980-4d9f-11e9-9b81-345ebff8b9af.jpg)

**Comment by stevu236** [comment]
We've started making improvements on this boss. Initial changes in 6f91edd201c504cae8946c5030140bcc5c4f5d5f

The scenario of this boss is now that there is a gas leak, hence you reason to escape. All areas except for the win area now degrade your HP, giving an unwritten timelimit to this boss as well as a motivator.

**Comment by stevu236** [comment]
We have added horizontal platforms as well to this boss and have released the changes in 2019.1 update - as such, I am going to close this issue. If you have further feedback regarding this boss, please raise another issue for further enhancements to be made.
