### ISSUE TITLE
Beatblock boss suggestion

### ISSUE THREAD

**Issue by UrUgli** [gemidyne/microtf2#74]
Some beatblocks are actually jumpable before the switch even came if done right, kinda ruins the whole "rythm" in my opinion and can make stuff easier and faster for others. Some parts are also way too easy since you can just go in the middle safely.

![20190323192047_1_LI](https://user-images.githubusercontent.com/45695904/54870000-f14d6c80-4da0-11e9-8734-92c74915ec88.jpg)

![20190323192054_1_LI](https://user-images.githubusercontent.com/45695904/54870007-0b874a80-4da1-11e9-9a83-bef29752b8a8.jpg)
![20190323192109_1_LI](https://user-images.githubusercontent.com/45695904/54870008-0d510e00-4da1-11e9-96ac-3c184472eb2d.jpg)

What i'm asking is to seperate the block enough so it isn't possible and make the boss more challenging (like all boss should be)

**Comment by Mario6493** [comment]
I don't think being able to jump ahead is a bad thing, if you want to risk the jump to skip a block ahead you should be free to do so

There's no bonus for finishing the course first anyways

And about the "easy" parts: 
The one in the bottom screenshot is right at the start of the course and is useful for teaching players how the switching works without risking too much

The one in the second screenshot is barely a staircase that connects to the next part of the course, I could split it in two but it's not really meant to be difficult

**Comment by UrUgli** [comment]
Oh i see, i'm just asking for this since, for me, some parts are just easy for the sake of being easy, when it should get gradually harder. But that's just my opinion

**Comment by stevu236** [comment]
If nothing is to come of this issue, can we close it off?

**Comment by UrUgli** [comment]
Yeah, go ahead.
