### ISSUE TITLE
Remove "double jump" minigame

### ISSUE THREAD

**Issue by UrUgli** [gemidyne/microtf2#78]
This minigame is really useless, it's basically a free point to press jump twice. An idea i have to replace it would be, "Crouch THEN jump", making it a bit more complex but still keeping it simple.

**Comment by UrUgli** [comment]
No

**Comment by stevu236** [comment]
I don't think replacing it with "crouch then jump" is a solution. Its still more or less the same thing: you're getting a point for doing nothing really.

**Comment by UrUgli** [comment]
I wanted to go for the same style, so i didn't think further than that. Will do
