### ISSUE TITLE
"Birds" special round suggestion

### ISSUE THREAD

**Issue by UrUgli** [gemidyne/microtf2#80]
Birds should actually be floating at a certain height (around the hips of the mercenarys) and not on the ground to make stuff like killing a bit more easier.

**Comment by stevu236** [comment]
This might be solved by #65 when its implemented though..

**Comment by stevu236** [comment]
I'm going to close this issue as duplicate because #65 is now the more general issue regarding the Birds special round. Please add any comments you may have to that issue.

#65 is already planning for using a full size custom model if possible so hitboxes would line up better for this.
