### ISSUE TITLE
Kamikaze does no damage

### ISSUE THREAD

**Issue by UrUgli** [gemidyne/microtf2#85]
As of today, while playing, i noticed that no matter the distance, kamikaze couldn't kill anyone thus automatically losing.

**Comment by stevu236** [comment]
We can't recreate this on our test server - What version of the plugin is the server you encountered this on running? If that server is running a developer build, we need confirmation from you or the server operator that the plugin is up to date with master.

Also, these cases might cause this issue: 
* The server you were playing on, has a plugin causing a conflict resulting in godmode in cases where it shouldn't
* The server you were playing on reloaded the plugin midway through the map, resulting in a partial load

**Comment by UrUgli** [comment]
I believe it was the RSX V1 version (Redsun version i believe)

**Comment by stevu236** [comment]
Oh, if I remember correctly, there was an issue with this before where the Redsun repo didn't get some changes from this repo. Possibly git automerge being a pain - this might be another one of those cases.

@EgocentricPoliceDick Could you check your version is in sync with master of this branch?

**Comment by stevu236** [comment]
We did more tests today and I can confirm the bug does not exist on gemidyne's version of the plugin, so this appears to be possibly an out-of-date version running on Redsun @UrUgli

**Comment by FortyTwoFortyTwo** [comment]
I also not sure why `SlapPlayer` doesn't kill players while other minigames work, but i used `ForcePlayerSuicide` instead and it works

**Comment by stevu236** [comment]
Thats weird - could another plugin be conflicting? 

I am going to close this issue for now as it does not seem to be an issue with gemidyne's version of the plugin. Feel free to reopen if need be
