### ISSUE TITLE
Hit someone! Minigame

### ISSUE THREAD

**Issue by Mario6493** [gemidyne/microtf2#93]
Everyone is a 30HP Scout equipped with a Boston Basher, the objective is simply to hit someone else
Missing causes the player to bleed to death

**Comment by UrUgli** [comment]
I think it'd be neat, but then the "Hit a heavy" minigame (with the medics) would just be a redundant hit someone minigame mechanic, so either add this one, or keep the other. That's my opinion

**Comment by Mario6493** [comment]
This and the Hit the Heavy minigame work in a completely different way, the former requires only one team to hit someone on the other team, this one has everyone trying to hit an enemy, with missing resulting in death

**Comment by stevu236** [comment]
> 
> 
> This and the Hit the Heavy minigame work in a completely different way, the former requires only one team to hit someone on the other team, this one has everyone trying to hit an enemy, with missing resulting in death

I agree, the basis of the minigames are different - one requires teamwork whilst the other is a free-for-all

**Comment by stevu236** [comment]
Aiming for this to be included in 2019.2, but if takes too much effort will be deferred to 2019.3

**Comment by stevu236** [comment]
Post-testing issues: 

- [ ] Need to investigate why bleed does not work after swing and miss
