### ISSUE TITLE
Don't Laugh! Minigame

### ISSUE THREAD

**Issue by Mario6493** [gemidyne/microtf2#94]
Everyone is a Heavy equipped with crit boosted mittens, getting hit causes players to laugh and fail the minigame

**Comment by stevu236** [comment]
This looks like it shouldn't take too long to do, will look to get this done for 2019.2, but if it turns out it will take more time, it will need to be moved for 2019.3.

**Comment by stevu236** [comment]
- [ ] Need to get BGM chosen for this minigame

**Comment by Mario6493** [comment]
Maybe this should be changed to "Make someone laugh!" instead as I've noticed that most players just try to stay away from everyone else in fear they get attacked
