### ISSUE TITLE
Add natives for other plugins to consume

### ISSUE THREAD

**Issue by stevu236** [gemidyne/microtf2#95]
This will allow for tighter integrations with other server plugins.

Some natives that should be added are for things like:
* Winning or losing a minigame
* Winning or losing a bossgame
* Winning or losing the round
* Gamemode state change (possibly diagnostic use?)

**Comment by FortyTwoFortyTwo** [comment]
Another native i'd like to suggest is to get current and max round gamemode is currently at, and allow to change/increase max round during mid-game.

Server we use have a custom mapvote, not using `umc-core` or `mapchooser` so we'd need to know when is a good moment to start a mapvote.

**Comment by stevu236** [comment]
Makes sense - I have been wanting to make separate "stock" plugins for things like the intermission. Having fwds/natives for it would make it better because then the main plugin can handoff to a subplugin to handle the voting process and then let the main plugin know when to resume gameplay

**Comment by stevu236** [comment]
Tested as working - but not added all forwards yet. Core player forwards implemented so far. 

Need to add:
[ ] GetMaxRounds
[ ] SetMaxRounds
[ ] OnGamemodeChanged (id, string)
[ ] OnSpeedChange (new speed)
[ ] OnSpecialRoundSelected (id)

**Comment by stevu236** [comment]
I've tested this - it seems to be working fine. However my test plugin wasn't properly ending the mapvote which made me worry a little that it working before was a fluke. It was returning true for "HasMapVoteEnded" but for some reason it kept waiting and didn't advance 

I need to do more testing on that part of this ticket - however the other forwards appear to working correctly.

**Comment by stevu236** [comment]
Tested further, everything is working fine. There was a logic bug due to the slightly different nature of the method compared to what it was before.
